name: Action test on Ubuntu

on:
  schedule:
    - cron: "0 2 * * MON-FRI" # Runs at 02:00 UTC
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Save date env variable
        run: echo "date=$(date)" >> $GITHUB_ENV
        shell: bash
      
      - name: Write simple value to test.properties file
        uses: GuillaumeFalourd/write-java-properties-file@main
        with:
          file_path: ${{github.workspace}}/test/test.properties
          property: date.key
          value: ${{ env.date }}

      - name: Write multiple values to test.properties file
        uses: GuillaumeFalourd/write-java-properties-file@main
        with:
          file_path: ${{github.workspace}}/test/test.properties
          property: |
            first.property.key
            second.property.key
          value: |
            first value
            second value
        
      - name: Show updated file
        run: cat ${{github.workspace}}/test/test.properties
        shell: bash